services:
  app:
    image: vaultwarden/server:1.29.2
    restart: always
    volumes:
      - data:/data
    environment:
      - SIGNUPS_ALLOWED=false
      - SHOW_PASSWORD_HINT=false
      - ADMIN_TOKEN
      - DOMAIN
      - SMTP_HOST
      - SMTP_FROM
      - SMTP_PORT
      - SMTP_SECURITY
      - SMTP_USERNAME
      - SMTP_PASSWORD
    networks:
      - default
      
  web:
    build: ./web
    restart: always
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - default
      - proxy
    depends_on:
      - app

volumes:
  data:

networks:
  proxy:
    name: nginx-proxy
    external: true
